SELECT
    B.BOOK_ID AS BOOK_ID,
    A.AUTHOR_NAME AS AUTHOR_NAME,
    TO_CHAR(B.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLIHSED_DATE
FROM BOOK B
         LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY =  '경제'
ORDER BY PUBLISHED_DATE ASC
;