SELECT
    CD.CAR_ID AS CAR_ID,
    TO_CHAR(ROUND(AVG(CD.DURATION),1), 'FM9999990.09') AS AVERAGE_DURATION
FROM
    (
        SELECT
            C.CAR_ID,
            (C.END_DATE - C.START_DATE+1) AS DURATION
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    ) CD
GROUP BY CAR_ID
HAVING AVG(CD.DURATION) >= 7
ORDER BY TO_NUMBER(AVERAGE_DURATION) DESC, CAR_ID DESC
;