WITH WRITER_AND_SALES AS (
    SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
)
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER
         INNER JOIN WRITER_AND_SALES
                    ON USER_ID = WRITER_ID
ORDER BY TOTAL_SALES ASC