SELECT
    '/home/grep/src/' || B.BOARD_ID || '/' || F.FILE_ID || F.FILE_NAME || F.FILE_EXT AS FILE_PATH
FROM (
         SELECT *
         FROM USED_GOODS_BOARD
         ORDER BY VIEWS DESC
         FETCH FIRST 1 ROW ONLY
     ) B
JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
ORDER BY F.FILE_ID DESC