WITH MAX_PER_CATEGORY AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)
SELECT FP.CATEGORY, MPC.MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
         JOIN MAX_PER_CATEGORY MPC
              ON FP.CATEGORY = MPC.CATEGORY
                  AND FP.PRICE = MPC.MAX_PRICE
WHERE FP.CATEGORY IN ('과자', '김치', '국', '식용유')
ORDER BY max_price DESC
;