WITH ALL_SALES AS (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE SALES_DATE >= TO_DATE('2022-03-01', 'YYYY-MM-DD')
      AND SALES_DATE < TO_DATE('2022-04-01', 'YYYY-MM-DD')

    UNION ALL

    SELECT SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE SALES_DATE >= TO_DATE('2022-03-01', 'YYYY-MM-DD')
      AND SALES_DATE < TO_DATE('2022-04-01', 'YYYY-MM-DD')
)
SELECT
    TO_CHAR(ALL_SALES.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM ALL_SALES
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC
;