WITH TRUCK_PRICE AS (
    SELECT CAR_ID, DURATION_TYPE, TRUNC(DAILY_FEE * (1 - DISCOUNT_RATE/100)) DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
             LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                       ON CAR_RENTAL_COMPANY_CAR.CAR_TYPE = CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE
    WHERE CAR_RENTAL_COMPANY_CAR.CAR_TYPE = '트럭'

    UNION
    SELECT CAR_ID, '7일 미만' DURATION_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
)
SELECT HISTORY_ID, (END_DATE - START_DATE + 1)* DAILY_FEE FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
         INNER JOIN TRUCK_PRICE
                    ON CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = TRUCK_PRICE.CAR_ID
                        AND DURATION_TYPE =
                            CASE
                                WHEN END_DATE - START_DATE + 1 < 7 THEN '7일 미만'
                                WHEN END_DATE - START_DATE + 1 < 30 THEN '7일 이상'
                                WHEN END_DATE - START_DATE + 1 < 90 THEN '30일 이상'
                                ELSE '90일 이상'
                                END
ORDER BY FEE DESC, HISTORY_ID DESC